import { ServiceItem } from './types';

export const MOCK_PROMOTIONS: ServiceItem[] = [
  {
    id: 'promo-01',
    name: 'O Poderoso Chefão',
    price: 'R$ 140,00',
    priceValue: 140,
    duration: '1h 30m',
    description:
      'A experiência definitiva de poder. Corte Premium + Barba Terapia com toalha quente e massagem facial + Sobrancelha. Inclui uma dose de Whisky Importado.',
    category: 'Combo',
    imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80',
    featured: true,
    discountPercentage: 15,
  },
  {
    id: 'promo-02',
    name: 'Dia do Noivo - Trilha',
    price: 'R$ 350,00',
    priceValue: 350,
    duration: '3h',
    description:
      'Preparação completa para o grande dia. Corte, Barba, Limpeza de Pele Profunda, Massagem Relaxante e Peeling Capilar. Sala VIP reservada com video-game e bebidas.',
    category: 'Especial',
    imageUrl: 'https://images.unsplash.com/photo-1507081323647-4d250478b919?w=800&q=80',
    featured: true,
    tag: 'Premium',
  },
  {
    id: 'promo-03',
    name: 'Pai & Filho (Legado)',
    price: 'R$ 90,00',
    priceValue: 90,
    duration: '1h',
    description:
      'Momentos que ficam para sempre. Corte para o pai e para o filho com desconto especial. Um tempo de qualidade na cadeira da barbearia.',
    category: 'Combo',
    imageUrl: 'https://images.unsplash.com/photo-1599351431202-1e0f0137eb1c?w=800&q=80',
    featured: true,
    discountPercentage: 10,
  },
  {
    id: 'promo-04',
    name: 'Barba Terapia VIP',
    price: 'R$ 60,00',
    priceValue: 60,
    duration: '45m',
    description:
      'Não é só fazer a barba, é um ritual. Vapor de ozônio, esfoliação facial, óleos essenciais e toalha quente aromatizada. Relaxe enquanto cuidamos do seu visual.',
    category: 'Barba',
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&q=80',
    featured: true,
  },
  {
    id: 'promo-05',
    name: 'Nevou (Platinado)',
    price: 'R$ 180,00',
    priceValue: 180,
    duration: '2h 30m',
    description:
      'O visual que para o trânsito. Descoloração global segura, matização para o tom branco gelo perfeito e hidratação pós-química.',
    category: 'Química',
    imageUrl: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&q=80',
    featured: true,
    tag: 'Trending',
  },
  {
    id: 'promo-06',
    name: 'Camuflagem de Brancos',
    price: 'R$ 80,00',
    priceValue: 80,
    duration: '40m',
    description:
      'Rejuvenesça 5 anos em 40 minutos. Pigmentação sutil para disfarçar os fios brancos da barba ou cabelo sem deixar aquele aspecto artificial "pintado".',
    category: 'Cabelo',
    imageUrl: 'https://images.unsplash.com/photo-1593702295094-aea22597af65?w=800&q=80',
    featured: true,
  },
  {
    id: 'promo-07',
    name: 'Combo Executivo',
    price: 'R$ 75,00',
    priceValue: 75,
    duration: '50m',
    description:
      'Para quem não tem tempo a perder. Corte Social + Acabamento de Barba rápido + Lavagem revigorante. Saia pronto para a reunião.',
    category: 'Combo',
    imageUrl: 'https://images.unsplash.com/photo-1517832606299-7ae9b720a186?w=800&q=80',
    featured: true,
  },
  {
    id: 'promo-08',
    name: 'Corte + Sobrancelha Premium',
    price: 'R$ 55,00',
    priceValue: 55,
    duration: '45m',
    description:
      'O detalhe que muda tudo. Corte moderno (Degradê/Fade) alinhado com o design de sobrancelha na navalha ou pinça.',
    category: 'Combo',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-befbb7470d03?w=800&q=80',
    featured: true,
    discountPercentage: 20,
  },
  {
    id: 'promo-09',
    name: 'Limpeza de Pele Black Mask',
    price: 'R$ 70,00',
    priceValue: 70,
    duration: '40m',
    description:
      'Remoção de cravos e impurezas com a famosa máscara negra de carvão ativado. Pele limpa, sem oleosidade e renovada.',
    category: 'Estética',
    imageUrl: 'https://images.unsplash.com/photo-1570172619643-4b96d0d4b94f?w=800&q=80',
    featured: true,
  },
  {
    id: 'promo-10',
    name: 'Alisamento Americano',
    price: 'R$ 50,00',
    priceValue: 50,
    duration: '40m',
    description:
      'Relaxe os fios e facilite o penteado do dia a dia. Ideal para quem quer reduzir o volume e manter o corte alinhado por mais tempo.',
    category: 'Química',
    imageUrl: 'https://images.unsplash.com/photo-1552377461-1e96a2f8d839?w=800&q=80',
    featured: true,
  },
  {
    id: 'promo-11',
    name: 'Tratamento Queda Zero',
    price: 'R$ 120,00',
    priceValue: 120,
    duration: '1h',
    description:
      'Sessão de argiloterapia e massagem estimulante no couro cabeludo para fortalecer os fios e combater a queda. Tecnologia e natureza juntas.',
    category: 'Tratamento',
    imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80',
    featured: true,
    tag: 'Saúde',
  },
  {
    id: 'promo-12',
    name: 'Acabamento "Pezinho" Grátis',
    price: 'R$ 0,00',
    priceValue: 0,
    duration: '10m',
    description:
      'Exclusivo para membros do Clube VIP. Passe aqui apenas para alinhar o pezinho e manter o corte em dia entre as visitas completas.',
    category: 'Cortesia',
    imageUrl: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=800&q=80',
    featured: true,
    tag: 'Clube VIP',
  },
];
